# This is a basic workflow to help to build a .Net project

name: Build .Net project

on:
  push:
    branches: [ main ]    

env:
  PROJECT_FILE: mitoSoft.homeNet.WebApps.Flow.csproj
  PROJECT_FOLDER: mitoSoft.homeNet.WebApps.Flow
  
jobs:
  deploys:
    runs-on: windows-latest
    steps:     
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      
      - run: dotnet restore ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }}
      
      - run: dotnet build ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }} -c Release --no-restore
      
      #- run: dotnet publish ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build
      #- run: dotnet publish ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }} -c Release
